title = "Ryuki Shimada"
author = "Ryuki Shimada"
baseURL = "https://rieuky.github.io"
languageCode = "en-us"

theme = "hugo-blog-awesome"

enableEmoji = true
ignoreErrors = ["additional-script-loading-error"]

[params]
    goToTop = true
    defaultColor = "dark"

[params.author]
    avatar = "profile.png"
    intro = "Ryuki Shimada"
    name = "Ryuki Shimada"
    description = "Make it work, make it right, make it fast."

[menu]
    [[menu.main]]
        pageRef = "/"
        name = "Home"
        url = "/"
        weight = 10
    [[menu.main]]
        pageRef = "publications"
        name = "Publications"
        url = "/publications/"
        weight = 20
    [[menu.main]]
        pageRef = "about"
        name = "About"
        url = "/about/"
        weight = 40

[[params.socialIcons]]
name = "github"
url = "https://github.com/rieuky"

[[params.socialIcons]]
name = "googlescholar"
url = "https://scholar.google.co.jp/citations?user=Az5KGOYAAAAJ&hl=en"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/ryuki-shimada-60790a16a/"

[[params.socialIcons]]
name = "email"
url = "mailto:ryukishimada218@keio.jp"
